ide-migration/js/migration-launch.js, ide-migration/partials/hana-credentials.html, ide-migration/partials/neo-credentials.html
Related to: https://github.com/SAP/xsk/issues/374
=> feat: change migration labels

ide-migration/js/neo-credentials.js, ide-migration/partials/neo-credentials.html
Related to: https://github.com/SAP/xsk/issues/373
I have implemented the user region input to be similar to the way you create branches in GitHub:
=> feat: add neo region dropdown

ide-migration/js/delivery-unit.js, ide-migration/js/hana-credentials.js, ide-migration/partials/hana-credentials.html, ide-migration/server/migration/api/migration-rest-api.js, ide-migration/server/migration/api/neo-databases-service.js, ide-migration/server/migration/process/list-available-databases-task.js, ide-migration/server/migration/process/migrationProcess.bpmn
Fixes: https://github.com/SAP/xsk/issues/254
=> feat: list available databases

ide-migration/js/delivery-unit.js, ide-migration/migration-launch.html, ide-migration/partials/delivery-unit.html
Solution for [issue 472](https://github.com/SAP/xsk/issues/472).
=> Added option to create new workspace.

ide-migration/server/migration/api/migration-service.js
Fixes: https://github.com/SAP/xsk/issues/719
=> fix: do not create hdi and hdiconfig everytime

ide-migration/extensions/migration-launch.extension, ide-migration/js/delivery-unit.js, ide-migration/js/neo-credentials.js, ide-migration/js/start-migration.js, ide-migration/migration-launch.html, ide-migration/migration-perspective.html, ide-migration/partials/hana-credentials.html, ide-migration/partials/neo-credentials.html, ide-migration/services/migration-perspective-view.js
Fixes https://github.com/SAP/xsk/issues/724
=> Address feedack

ide-migration/extensions/migration-statistic.extension, ide-migration/js/migration-perspective.js, ide-migration/js/migration-statistic.js, ide-migration/migration-statistic.html, ide-migration/server/migration/api/migration-rest-api.js, ide-migration/server/migration/api/track-service.js, ide-migration/server/migration/process/close-hana-tunnel-task.js, ide-migration/server/migration/process/copy-files-task.js, ide-migration/server/migration/process/create-workspace-task.js, ide-migration/server/migration/process/handle-deployables-task.js, ide-migration/server/migration/process/list-available-databases-task.js, ide-migration/server/migration/process/list-delivery-units-task.js, ide-migration/server/migration/process/list-workspaces-task.js, ide-migration/server/migration/process/open-hana-tunnel-task.js, ide-migration/server/migration/process/populate-projects-task.js, ide-migration/services/migration-statistic-view.js
Migration status tracker added.
=> migration status tracker

ide-migration/server/migration/api/calculationViewModifierService.js, ide-migration/server/migration/api/migration-service.js, ide-migration/server/migration/process/populate-projects-task.js
- remove type artifact from calculationview/hdbcalculationview
=> - fix #913

ide-migration/server/migration/api/migration-service.js, ide-migration/server/migration/process/populate-projects-task.js
include XSKProjectMigrationInterceptor for localizing in the future all files modifications in one place.
=> XSKProjectMigrationInterceptor

ide-migration/server/migration/process/populate-projects-task.js
Temporary workaround for: https://github.com/eclipse/dirigible/issues/1437
=> fix: temporarily use the java git facade directly

ide-migration/server/migration/api/HanaVisitor.js, ide-migration/server/migration/api/migration-service.js, ide-migration/server/migration/process/populate-projects-task.js
Implements https://github.com/SAP/xsk/issues/791
Fixes https://github.com/SAP/xsk/issues/998
Fixes https://github.com/SAP/xsk/issues/1023
Depends on https://github.com/SAP/xsk/pull/1025 and https://github.com/eclipse/dirigible/pull/1449
=> [DO NOT MERGE]Move hdbtablefunction in HDI container

ide-migration/server/migration/api/migration-service.js, ide-migration/server/migration/process/populate-projects-task.js
This PR fixes handling/modification for multiple projects in a delivery unit.
=> work on handle all the projects and modifying all files of a  du

ide-migration/server/migration/api/migration-service.js, ide-migration/server/migration/repository/hdi-plugins.js
Enable all plugins by default in the hdiconfig.
=> Enable plugins in the hdiconfig.

ide-migration/server/migration/repository/hdi-plugins.js
remove version for hdiconfig plugins.
code formatting.
=> Code clean up

ide-migration/server/migration/api/hana-visitor.mjs, ide-migration/server/migration/api/migration-service.mjs, ide-migration/server/migration/repository/hdi-plugins.mjs
Fixes https://github.com/SAP/xsk/issues/1221
=> Fix quotation in hdbtablefunction

ide-migration/js/start-migration.js, ide-migration/js/zip-migration.js, ide-migration/server/migration/api/migration-service.mjs
Improved error handling, fixed https://github.com/SAP/xsk/issues/1048 and https://github.com/SAP/xsk/issues/1230
Typo found in migration-service fixed.
=> XSK issues #1048, #1230

ide-migration/server/migration/api/migration-service.mjs
Synonym generation changes:
* Hdbpublicsynonym is generated ONLY for tablefunction and calculationview.
* Hdbsynonym is not generated for tablefunction and calculationview.
* Hdbsynonym is generated for any other `PARSED` artifact.
=> Fix: filter artifacts when generating synonyms

ide-migration/js/delivery-unit.js, ide-migration/js/hana-credentials.js, ide-migration/server/migration/api/migration-rest-api.mjs, ide-migration/server/migration/api/migration-service.mjs, ide-migration/server/migration/process/copy-files-task.mjs, ide-migration/server/migration/process/handle-deployables-task.mjs, ide-migration/server/migration/process/migrationProcess.bpmn, ide-migration/server/migration/process/open-hana-tunnel-task.mjs, ide-migration/server/migration/process/populate-projects-task.mjs, ide-migration/server/migration/repository/hana-repository.mjs
Implements https://github.com/SAP/xsk/issues/1163
Fixes https://github.com/SAP/xsk/issues/1187
=> Move list databases task to rest endpoint / Fix empty DU error

ide-migration/migration-launch.html, ide-migration/migration-perspective.html
Signed-off-by: StanZGenchev <stanislav.genchev@sap.com>
Updated jQuery reference
=> Updated jQuery reference

ide-migration/server/migration/process/populate-projects-task.mjs
Fixes https://github.com/SAP/xsk/issues/1389
=> Fix populate projects task closing on empty DU

ide-migration/server/migration/api/migration-service.mjs, ide-migration/server/migration/process/handle-deployables-task.mjs
Fixes: https://github.com/SAP/xsk/issues/1414
=> fix: make group and container values in hdi uppercase

.gitignore, ide-migration/js/changes.js, ide-migration/migration-launch.html
Fix for Dirigible issue:
https://github.com/eclipse/dirigible/issues/1723
Should be merged after the next Dirigible version is merged in XSK.
=> Fix dg 1723

ide-migration/server/migration/api/migration-rest-api.mjs
=> get oauth access token with POST

ide-migration/js/changes.js, ide-migration/js/delivery-unit.js, ide-migration/js/hana-credentials.js, ide-migration/js/migration-flow.js, ide-migration/js/migration-launch.js, ide-migration/js/migration-state-manager.js, ide-migration/js/migration-view-state.js, ide-migration/js/neo-credentials.js, ide-migration/js/start-migration.js, ide-migration/js/step-factory.js, ide-migration/js/zip-migration.js, ide-migration/migration-launch.html, ide-migration/partials/changes.html, ide-migration/partials/delivery-unit.html, ide-migration/partials/hana-credentials.html, ide-migration/partials/migration-statistic.html, ide-migration/partials/neo-credentials.html, ide-migration/partials/start-migration.html, ide-migration/partials/zip-migration.html, ide-migration/server/migration/api/migration-rest-api.mjs, ide-migration/server/migration/api/migration-service.mjs, ide-migration/server/migration/api/track-service.mjs, ide-migration/server/migration/migration.changelog, ide-migration/server/migration/process/after-migration-task.mjs, ide-migration/server/migration/process/copy-files-task.mjs, ide-migration/server/migration/process/handle-deployables-task.mjs, ide-migration/server/migration/process/migrationProcess.bpmn, ide-migration/server/migration/process/populate-projects-task.mjs, ide-migration/server/migration/process/unzip-to-temporary-folder-task.mjs
1. Tracking project files by passing array with objects metadata causes memory issues, so now we are getting this metadata on demand.
2. Add continue button to finish the migration if session expires or tab is closed
3. Refactor steps handling
=> Refactor steps and enable continuing after session end

ide-migration/server/migration/api/migration-service.mjs
fixes https://github.com/SAP/xsk/issues/735
=> Create xs-security.json from xsprivileges

ide-migration/server/migration/api/migration-service.mjs
=> fix migration when DIRIGIBLE_OAUTH_APPLICATION_NAME is null.

ide-migration/server/migration/api/migration-service.mjs
Signed-off-by: dimitarquanterall <d.aleksandrov@sap.com>
Rename any *.calculationview file found to *.hdbcalculationview during migration
Fixes https://github.com/SAP/xsk/issues/1608, https://github.com/SAP/xsk/issues/1609
=> Fix #1608, #1609
